import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TextInput, TouchableOpacity, Alert } from 'react-native';
import { COLORS, SIZES } from '../../constants/theme';
import { Header, Card, Button, Badge } from '../../components';

const DraftApprovalScreen = ({ navigation, route }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [draftText, setDraftText] = useState(
    "Hi Sarah,\n\nThanks for following up! I've reviewed the Q1 contract and everything looks good. I'll have it signed and sent back to you within the hour.\n\nBest,\nJohn"
  );

  const handleApprove = () => {
    Alert.alert(
      'Email Sent',
      'Your reply has been sent successfully!',
      [{ text: 'OK', onPress: () => navigation.goBack() }]
    );
  };

  const handleReject = () => {
    Alert.alert(
      'Draft Rejected',
      'The draft has been discarded.',
      [{ text: 'OK', onPress: () => navigation.goBack() }]
    );
  };

  return (
    <View style={styles.container}>
      <Header
        variant="orange"
        title={"DRAFT\nREVIEW"}
        showBack={true}
        onBackPress={() => navigation.goBack()}
        rightComponent={<Badge text="AI Generated" variant="ai" />}
      />

      <ScrollView 
        style={styles.content}
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={false}
      >
        {/* Original Thread */}
        <Text style={styles.sectionLabel}>Original Thread</Text>
        <Card variant="outlined" style={styles.originalCard}>
          <View style={styles.senderRow}>
            <View style={styles.senderAvatar}>
              <Text style={styles.senderInitials}>SC</Text>
            </View>
            <View style={styles.senderInfo}>
              <Text style={styles.senderName}>Sarah Chen</Text>
              <Text style={styles.senderEmail}>sarah@acme.com</Text>
            </View>
          </View>
          <Text style={styles.originalText}>
            Hi, just following up on the Q1 contract. We need your signature by EOD today. Can you please review and confirm?
          </Text>
          <Text style={styles.originalTime}>Today at 9:15 AM</Text>
        </Card>

        {/* AI Draft */}
        <Text style={styles.sectionLabel}>AI Drafted Response</Text>
        <Card variant="lavender">
          <View style={styles.draftHeader}>
            <View style={styles.aiAvatar}>
              <Text style={styles.aiIcon}>🤖</Text>
            </View>
            <View style={styles.draftInfo}>
              <Text style={styles.draftTitle}>Your Reply</Text>
              <Text style={styles.draftSubtitle}>Generated by Comm Manager</Text>
            </View>
          </View>
          
          {isEditing ? (
            <TextInput
              style={styles.draftInput}
              value={draftText}
              onChangeText={setDraftText}
              multiline
              autoFocus
            />
          ) : (
            <View style={styles.draftBody}>
              <Text style={styles.draftText}>{draftText}</Text>
            </View>
          )}

          <TouchableOpacity 
            style={styles.editToggle}
            onPress={() => setIsEditing(!isEditing)}
          >
            <Text style={styles.editToggleText}>
              {isEditing ? '✓ Done Editing' : '✏️ Edit Draft'}
            </Text>
          </TouchableOpacity>
        </Card>

        {/* Suggestions */}
        <Text style={styles.sectionLabel}>AI Suggestions</Text>
        <View style={styles.suggestions}>
          <TouchableOpacity style={styles.suggestionChip}>
            <Text style={styles.suggestionText}>Add signature</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.suggestionChip}>
            <Text style={styles.suggestionText}>More formal</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.suggestionChip}>
            <Text style={styles.suggestionText}>Add timeline</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>

      {/* Bottom Actions */}
      <View style={styles.bottomActions}>
        <Button
          title="Reject"
          variant="secondary"
          onPress={handleReject}
          style={{ flex: 0.3 }}
        />
        <Button
          title="✏️ Edit"
          variant="secondary"
          onPress={() => setIsEditing(true)}
          style={{ flex: 0.3 }}
        />
        <Button
          title="✓ Approve & Send"
          variant="primary"
          onPress={handleApprove}
          style={{ flex: 0.4 }}
        />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.gray,
  },
  content: {
    flex: 1,
    backgroundColor: COLORS.gray,
    borderTopLeftRadius: SIZES.radiusXl,
    borderTopRightRadius: SIZES.radiusXl,
    marginTop: -20,
  },
  contentContainer: {
    padding: SIZES.lg,
    paddingBottom: 120,
  },
  sectionLabel: {
    fontSize: SIZES.fontXs,
    fontWeight: '600',
    color: COLORS.textTertiary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: SIZES.sm + 2,
    marginTop: SIZES.lg,
  },
  originalCard: {
    backgroundColor: '#F9F9F9',
  },
  senderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.sm + 2,
    marginBottom: SIZES.md,
  },
  senderAvatar: {
    width: 36,
    height: 36,
    backgroundColor: COLORS.gray,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  senderInitials: {
    fontSize: SIZES.fontSm,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  senderInfo: {
    flex: 1,
  },
  senderName: {
    fontSize: SIZES.fontMd,
    fontWeight: '600',
    color: COLORS.black,
  },
  senderEmail: {
    fontSize: SIZES.fontSm - 1,
    color: COLORS.textSecondary,
  },
  originalText: {
    fontSize: SIZES.fontMd,
    color: COLORS.textSecondary,
    lineHeight: 22,
  },
  originalTime: {
    fontSize: SIZES.fontXs,
    color: COLORS.textTertiary,
    marginTop: SIZES.sm,
  },
  draftHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.sm + 2,
    marginBottom: SIZES.md,
  },
  aiAvatar: {
    width: 36,
    height: 36,
    backgroundColor: COLORS.white,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiIcon: {
    fontSize: 18,
  },
  draftInfo: {
    flex: 1,
  },
  draftTitle: {
    fontSize: SIZES.fontMd,
    fontWeight: '600',
    color: COLORS.white,
  },
  draftSubtitle: {
    fontSize: SIZES.fontSm - 1,
    color: 'rgba(255,255,255,0.7)',
  },
  draftBody: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: SIZES.radiusSm,
    padding: SIZES.md,
  },
  draftText: {
    fontSize: SIZES.fontMd,
    color: COLORS.white,
    lineHeight: 22,
  },
  draftInput: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radiusSm,
    padding: SIZES.md,
    fontSize: SIZES.fontMd,
    color: COLORS.black,
    lineHeight: 22,
    minHeight: 150,
    textAlignVertical: 'top',
  },
  editToggle: {
    alignSelf: 'flex-end',
    marginTop: SIZES.md,
  },
  editToggleText: {
    fontSize: SIZES.fontSm,
    color: COLORS.white,
    fontWeight: '600',
  },
  suggestions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SIZES.sm,
  },
  suggestionChip: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.black,
    borderRadius: SIZES.radiusFull,
    paddingVertical: SIZES.sm,
    paddingHorizontal: SIZES.md,
  },
  suggestionText: {
    fontSize: SIZES.fontSm,
    color: COLORS.black,
  },
  bottomActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.black,
    padding: SIZES.lg,
    flexDirection: 'row',
    gap: SIZES.sm,
  },
});

export default DraftApprovalScreen;
